### GET - pobierz same tagi
GET http://localhost:3000/api/tags/raw HTTP/1.1

### GET - pobierz objekty z tagami
GET http://localhost:3000/api/tags HTTP/1.1

### GET - pobierz 1 tag
GET http://localhost:3000/api/tags/3 HTTP/1.1

### POST - dodaj nowy tag
POST http://localhost:3000/api/tags HTTP/1.1

{   
    "tag": "#nowytag2",
    "popularity": 1000000    
}