### GET - pobierz meta dane
GET http://localhost:3000/api/filters/metadata/1683229305737469 HTTP/1.1


### PATCH /api/filters // użycie konkretnego filtra

PATCH http://localhost:3000/api/filters HTTP/1.1
content-type: application/json

{
    "id": 1684488436684489,
    "filter": "flop"
}

### GET /api/getfile/12345 - pobierz zdjęcie wg id

GET http://localhost:3000/api/getfile/12345 HTTP/1.1


### GET /api/getfile/12345/filtername - pobierz zdjęcie wg id i nazwy filtra

GET http://localhost:3000/api/getfile/12345/rotate HTTP/1.1