### POST - dodaj rejestracje usera

POST http://localhost:3000/api/user/register HTTP/1.1
content-type: application/json

{    
   "name": "name",
   "lastName": "lastName",
   "email": "name@email.pl",
   "password": "password"
}

### GET - potwierdzenie rejestracji usera
GET http://localhost:3000/api/user/confirm/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbWVAZW1haWwucGwiLCJpYXQiOjE2ODQ0OTE2NjAsImV4cCI6MTY4NDQ5NTI2MH0.KUo6qsj0VQje5mEEhxRV1zfDnSGf_1AkNQcZgoTxC_o HTTP/1.1

### POST - dodaj logowanie usera

POST http://localhost:3000/api/user/login HTTP/1.1

{
    "email": "name@email.pl",
    "password": "password"
}

### GET - pobierz wszystkich userow

GET http://localhost:3000/api/user HTTP/1.1

