### POST - dodaj rejestracje usera

POST http://localhost:3000/api/user/register HTTP/1.1
content-type: application/json

{    
   "name": "name",
   "lastName": "lastName",
   "email": "name@email.pl",
   "password": "password"
}

### GET - potwierdzenie rejestracji usera
GET http://localhost:3000/api/user/confirm/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbWVAZW1haWwucGwiLCJsb2dpbiI6Im5vIiwiaWF0IjoxNjg1MzQ3NTAxLCJleHAiOjE2ODUzNTExMDF9.WghSRzeSVIpZ8eZ1etisGiv_kFjGXuloJ_Gxhx9Svlk HTTP/1.1

### POST - dodaj logowanie usera

POST http://localhost:3000/api/user/login HTTP/1.1

{
    "email": "name@email.pl",
    "password": "password"
}

### GET - pobierz wszystkich userow

GET http://localhost:3000/api/user HTTP/1.1

### GET - wyloguj usera

GET http://localhost:3000/api/user/logout HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbWVAZW1haWwucGwiLCJsb2dpbiI6InllcyIsImlhdCI6MTY4NTM0ODk0MywiZXhwIjoxNjg1MzUyNTQzfQ.v6nRN7mAkkSA-M8AidYTormv_ZnpApm0eqIUfC4EOvo